### PR TITLE
Remove support for Webpack 1

### LINKED ISSUE #15: Remove support for Webpack 1
Buble doesn't transpile `import`/`export` statements, making Buble _impossible_ to work with Webpack 1. Moreover, Webpack 2 already does this.

Alternatively, we can add a warning for Webpack 1 users about this.

### PR DESCRIPTION
**Pull request by srph**
Resolves #15

- Remove or (`||`) dependency on Webpack 1
- Add Webpack 2 requirement

### CODE REVIEW

**Comment by sairion** [comment]
Actually sorry, I misread your issue (I thought you meant to add just a simple warning). I don't think it is good idea to completely remove support for Webpack 1. There are still (a lot of) people whom using Webpack 1 and CommonJS/RequireJS modules, including me.

**Comment by srph** [comment]
My bad. Just curious: how are you able to accomplish this if Buble doesn't transpile import/export statements? Thanks!

**Comment by sairion** [comment]
@srph By avoiding use of import/export statement and libs using them? (But most of time I use Babel and import/export statement)

**Comment by srph** [comment]
Alright!

**Pull request closed without merging**
