### PR TITLE
Added support for ES6 module import and export for Webpack 1

### PR DESCRIPTION
**Pull request by nicko**

### CODE REVIEW

**Comment by srph** [comment]
Whoa nice :sparkles: , but should we be doing this out of the box? If yes, I can close #20 :D so we can proceed with this PR.

**Comment by nicko** [comment]
Yeah up to @sairion I guess but I can say that it was definitely something I was looking for when I found this loader. I'm stuck with Webpack1 for a project and if Buble and this loader could provide a drop-in replacement for Babel it would be really useful.

**Comment by nicko** [comment]
@sairion You ok to merge this?

**Comment by sairion** [comment]
Sorry, but I doubt this is a responsibility of this loader. I believe people can make their own loader/preloader/whatever to do this kind of transform and put this `buble-loader` after it. At least, I don't want to add another full-blown AST readers/transformers to deps for compat reason which doesn't seem to be a big problem.

**Pull request closed without merging**
